version: '2'
services:
    blog-app:
        image: blog
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://blog-mysql:3306/blog?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=blog-elasticsearch:9300
        ports:
            - 8080:8080
    blog-mysql:
        extends:
            file: mysql.yml
            service: blog-mysql
    blog-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: blog-elasticsearch
